import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Comp1 from './comp1'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
  
        <Comp1/>
       
       
        <main className='px-10'>{children}</main>
      
      </body>
     

    </html>
  )
}
